name: Python Unittest on Push and PR

on:
  push:
    branches: [ main, dev]
    paths: 
      - "torch_staintools/**"
      - 'tests/**'
      - "requirements.txt"
      - "setup.py"
  pull_request:
    branches: [ main ]
    paths: 
      - "torch_staintools/**"
      - 'tests/**'
      - "requirements.txt"
      - "setup.py"

jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ['3.10']  # Currently testing only with 3.10, but easy to add more

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run unittests
      run: python -m unittest discover -s tests
